{'name': 'root', 'msg': 'info\u30ec\u30d9\u30eb', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': '/tmp/ipykernel_57/165405198.py', 'filename': '165405198.py', 'module': '165405198', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 2, 'funcName': '<module>', 'created': 1630401334.331413, 'msecs': 331.41303062438965, 'relativeCreated': 70063925.64630508, 'thread': 139755469076288, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 57, 'message': 'info\u30ec\u30d9\u30eb'}sctime)s:INFO:infoレベル
{'name': 'root', 'msg': '\u8b66\u544a\u30ec\u30d9\u30eb', 'args': (), 'levelname': 'WARNING', 'levelno': 30, 'pathname': '/tmp/ipykernel_57/165405198.py', 'filename': '165405198.py', 'module': '165405198', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 3, 'funcName': '<module>', 'created': 1630401334.3407767, 'msecs': 340.7766819000244, 'relativeCreated': 70063935.00995636, 'thread': 139755469076288, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 57, 'message': '\u8b66\u544a\u30ec\u30d9\u30eb'}sctime)s:WARNING:警告レベル
{'name': 'root', 'msg': '\u30a8\u30e9\u30fc\u30ec\u30d9\u30eb', 'args': (), 'levelname': 'ERROR', 'levelno': 40, 'pathname': '/tmp/ipykernel_57/165405198.py', 'filename': '165405198.py', 'module': '165405198', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 4, 'funcName': '<module>', 'created': 1630401334.3413913, 'msecs': 341.39132499694824, 'relativeCreated': 70063935.62459946, 'thread': 139755469076288, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 57, 'message': '\u30a8\u30e9\u30fc\u30ec\u30d9\u30eb'}sctime)s:ERROR:エラーレベル
{'name': 'root', 'msg': '\u91cd\u5927\u306a\u30a8\u30e9\u30fc', 'args': (), 'levelname': 'CRITICAL', 'levelno': 50, 'pathname': '/tmp/ipykernel_57/165405198.py', 'filename': '165405198.py', 'module': '165405198', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 5, 'funcName': '<module>', 'created': 1630401334.3419323, 'msecs': 341.9322967529297, 'relativeCreated': 70063936.16557121, 'thread': 139755469076288, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 57, 'message': '\u91cd\u5927\u306a\u30a8\u30e9\u30fc'}sctime)s:CRITICAL:重大なエラー
{'name': 'root', 'msg': 'info\u30ec\u30d9\u30eb', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': '/tmp/ipykernel_57/165405198.py', 'filename': '165405198.py', 'module': '165405198', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 2, 'funcName': '<module>', 'created': 1630401372.0577302, 'msecs': 57.73019790649414, 'relativeCreated': 70101651.96347237, 'thread': 139755469076288, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 57, 'message': 'info\u30ec\u30d9\u30eb'}sctime)s:INFO:infoレベル
{'name': 'root', 'msg': '\u8b66\u544a\u30ec\u30d9\u30eb', 'args': (), 'levelname': 'WARNING', 'levelno': 30, 'pathname': '/tmp/ipykernel_57/165405198.py', 'filename': '165405198.py', 'module': '165405198', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 3, 'funcName': '<module>', 'created': 1630401372.0586345, 'msecs': 58.63451957702637, 'relativeCreated': 70101652.86779404, 'thread': 139755469076288, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 57, 'message': '\u8b66\u544a\u30ec\u30d9\u30eb'}sctime)s:WARNING:警告レベル
{'name': 'root', 'msg': '\u30a8\u30e9\u30fc\u30ec\u30d9\u30eb', 'args': (), 'levelname': 'ERROR', 'levelno': 40, 'pathname': '/tmp/ipykernel_57/165405198.py', 'filename': '165405198.py', 'module': '165405198', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 4, 'funcName': '<module>', 'created': 1630401372.059035, 'msecs': 59.03506278991699, 'relativeCreated': 70101653.26833725, 'thread': 139755469076288, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 57, 'message': '\u30a8\u30e9\u30fc\u30ec\u30d9\u30eb'}sctime)s:ERROR:エラーレベル
{'name': 'root', 'msg': '\u91cd\u5927\u306a\u30a8\u30e9\u30fc', 'args': (), 'levelname': 'CRITICAL', 'levelno': 50, 'pathname': '/tmp/ipykernel_57/165405198.py', 'filename': '165405198.py', 'module': '165405198', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 5, 'funcName': '<module>', 'created': 1630401372.0594647, 'msecs': 59.46469306945801, 'relativeCreated': 70101653.69796753, 'thread': 139755469076288, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 57, 'message': '\u91cd\u5927\u306a\u30a8\u30e9\u30fc'}sctime)s:CRITICAL:重大なエラー
